### ISSUE TITLE
Don't use hardcoded db configuration

### ISSUE THREAD

**Issue by AlphaBeth** [hieuminhvuu/Lab7#1]
https://github.com/hieuminhvuu/Lab7/blob/a83ad73f6d077b3662de4fa0f7098aab56a112ad/Server/src/main/java/Database/DatabaseCommunicator.java#L17

**Comment by AlphaBeth** [comment]
Your program can't be execute on other environment. Use configuration (environment variable, command line args, configuration files) to read actual db connection information.

**Comment by hieuminhvuu** [comment]
done
