### ISSUE TITLE
Avoid using static state

### ISSUE THREAD

**Issue by AlphaBeth** [hieuminhvuu/Lab7#3]
https://github.com/hieuminhvuu/Lab7/blob/a83ad73f6d077b3662de4fa0f7098aab56a112ad/Server/src/main/java/Database/SpaceMarineBase.java#L16

Make this instance field, not static

**Comment by hieuminhvuu** [comment]
done

**Comment by AlphaBeth** [comment]
No, you just move static connection to another class. Don't use static connection, make it instance field

**Comment by hieuminhvuu** [comment]
done
