### ISSUE TITLE
Don't use System.exit

### ISSUE THREAD

**Issue by AlphaBeth** [hieuminhvuu/Lab7#9]

**Comment by hieuminhvuu** [comment]
done

**Comment by AlphaBeth** [comment]
https://github.com/hieuminhvuu/Lab7/blob/fc74aa9d9d3f3451033494f43a1a64539f3328c0/Server/src/main/java/Database/DatabaseCommunicator.java#L56

**Comment by AlphaBeth** [comment]
And I see a lot of "System.exit" in other places.

**Comment by hieuminhvuu** [comment]
done

**Comment by AlphaBeth** [comment]
You just replace exit with halt, it isn't correct.
The problem with System.exit isn't in method itself. The problem is that it hard to find why your program have finished working, there are a lot of exit points.
